# Generated by Django 3.2.7 on 2021-09-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Continent',
            },
        ),
    ]
