# Generated by Django 3.2.7 on 2021-09-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_controller', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
