# Generated by Django 3.2.7 on 2021-09-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_controller', '0007_auto_20210912_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
